### ISSUE TITLE
Add timeline to stacked bar and stacked area charts

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1100]
## Problem

You can change the time settings on most chart types, but not on stacked bar or stacked area. But there's no specific reason for this, we just haven't implemented it.

## Tasks

- [ ] Add timeline to Stacked Bar charts
- [ ] Add timeline to Stacked Area charts (single year -> stacked bar)
- [ ] (optional) Stacked bar by date on single year becomes stacked discrete bar
- [ ] (optional) Faceted stacked bar becomes becomes stacked discrete bar on single year
- [ ] Verify whether we want it on old charts by default

**Comment by larsyencken** [comment]
Prioritised as "important" since we have a weird interface right now where you can change the timeline on the table tab, but not on the main chart.
