### ISSUE TITLE
Apply to be a Google Summer of Code host organisation

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1150]
We would like to host one or more interns over summer to contribute to open source projects of ours, especially Grapher or the ETL. Applications are due by Feb 21 for host organisations.

https://summerofcode.withgoogle.com/

## Todo

- [x] Sign up
- [x] Complete profile
- [x] Add a second org admin
- [x] Complete questionnaire
- [x] Create ideas list
- [x] Identify number of mentors available

**Comment by larsyencken** [comment]
Submitted our application today.
