### ISSUE TITLE
Tracking issue: scatterplot improvements

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1168]
## What

We have a number of requests from, including some from @maxroser, for making scatterplots better:

- [x] They should explain what the bubble size is
https://github.com/owid/owid-grapher/issues/1089
- [x] They should not label non-countries with ‘no data’ in the legend https://github.com/owid/owid-grapher/issues/1167
- [x] #1912
- [ ] They should have a y-axis label that is horizontal so that it is possible to add more text there.
    - One reason for this is that the FASTT system we are building – where each metric has a subtitle – does not work for our current scatter plots cause they have one subtitle for both metrics.
    - To solve this, scatter plots should be designed [like this](https://ourworldindata.org/uploads/2021/07/child-mortality-gdp-per-capita.png) –– i.e. they should *not* have one long subtitle referring to both metrics, but instead have two places where the two metrics can be explained. This will make it possible to manage to scatter plots via the FASTT system we are building.
- [x] The X and Y values for a point should be easier to read on hover (currently panel on bottom right changes, in very small font) https://github.com/owid/owid-grapher/issues/2087
- [x] #1690
- [x] #1691
- [ ] https://github.com/owid/owid-grapher/issues/1686
- [x] #1332
- [x] #1550

**Comment by larsyencken** [comment]
There were also some earlier ideas: https://www.notion.so/owid/Trajectory-scatter-improvements-d7e69137d8264f56b4010d9963778844

**Comment by danyx23** [comment]
Closing this issue as most of the sub-items have been fixed and we have follow-up issues for the remaining ones
