### ISSUE TITLE
Tracking issue: Github project automations

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1386]
## Desired automations

To make it easier to review and summarize what we got done:

- [ ] Any issue closed is assigned to the current cycle
- [ ] Any PR opened or closed is assigned to the current cycle

To make sure that we have good discipline around triage:

- [ ] Any open issue that is modified and is missing a prioritised or an estimate should be labelled as "needs triage" (unless it is a Concept, Proposal, Project, or Tracking Issue)

To make it easier to see the overview of current work:

- [ ] Any PR opened is set to status "Blocked" whilst waiting for review
- [ ] Any PR that receives review is then set to status "In Progress"
- [ ] Draft PRs opened or modified are set to status "In Progress"
- [ ] Draft PRs without changes for 1w are set to status "Todo"
- [ ] Any PR that is not updated in 2w gets a warning and is labelled "stale"
- [ ] Any PR that is stale for 3d is closed

To make it easier to manage our backlog:

- [ ] Degrade priority of all issues after 60 days of inactivity and a 7 day warning (essential -> important; important -> nice to have; nice to have -> closed as wontfix); ignored for issues marked as `pinned` or `security`

**Comment by GermaVinsmoke** [comment]
Hey @larsyencken is this still open? If yes, I'd like to work on this 😀

**Comment by GermaVinsmoke** [comment]
Okay makes sense. Are there any issues on which I can work in order to become familiar with the project?
