### ISSUE TITLE
Project: Details on Demand

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1448]
This project is about creating an on hover feature for subtitles in Grapher to give more context (e.g. to give the definition of GDP or international dollars) - similar to the on-hover previews that Wikipedia has.

![image](https://user-images.githubusercontent.com/11844404/170355720-cb6d51b4-96b9-414b-b1a3-75acd3e688c1.png)

The feature is described in more detail in [this presentation](https://docs.google.com/presentation/d/1XoQKTkACEcdjs2nk3K1pehloZreOIF-ThA5N-csQs-g/edit#slide=id.p).

## Tasks
- [x] #1467
- [x] #1469
  - [x] Validate DoD references to prevent deletion of DoDs that are in-use
- [x] #1472
- [ ] DoD Baking
  - [x] #1482
  - [x] #1494
  - [ ] Notify on Slack if a DoD has no data / is unset
- [ ] DoD viewer components
  - [x] #1497
  - [x] #1507
  - [x] Display DoDs on static chart export
  - [ ] TextWrap support for italics and anchor links with linebreaks

**Comment by ikesau** [comment]
Running list of further TODOs that have been identified in pull requests:
- [ ] Automatically update suggested chart revisions so that they don't invalidate when a DoD is updated
- [ ] Support variable-level grapher configs
- [ ] Validate subtitle and note updates from the bulk editor

**Comment by ikesau** [comment]
V1 of Details on Demand is now deployed on staging where I shall continue to QA it until we think it's ready for a deployment onto prod.

**Comment by larsyencken** [comment]
This round of this project concluded, closing the issue. Feel free to open a new tracking issue with further details on demand work.
