### ISSUE TITLE
Project: prototype authoring via Google Docs

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1459]
## What?

A usable prototype that allows authors to create an article directly from a Google Doc. The goal will be to hand off something to authors that simulates the experience of using this to create real articles on the site. We will use it to evaluate investing more time to switching over to this approach.

## Why?

The current system of publishing articles is rough because it requires copying content back and forth between GDocs and WordPress. This approach makes GDocs the source of truth, and has the nice benefit that we will have a more structured representation of articles, making it easier to add additional component types in the future.

## Why now?

We want to ease the burden of creating and maintaining articles as much as possible, and we think this approach will help achieve that, but we need to de-risk it through a prototype first.

## In scope

Guessing, in advance of conversations with Joe

- [x] Setting up an admin site on hosting
- [x] Simple markup support (bold, italic)
- [ ] Layout support (???)
- [ ] Run workshop with authors introducing it, get feedback

## Not in scope

- Integrating into baking (necessary for production)

## Milestones

- [ ] June 3: Required features defined w/ Joe
- [ ] June 24: Working implementation
- [ ] July 1: Working deployment

## Risks

- The prototype isn’t high fidelity enough to give authors a sense of if this is useful for them
- The implementation is not finished

**Comment by larsyencken** [comment]
Closing this now, superseded by further projects.
