### ISSUE TITLE
Tracking issue: make auto-translation easier for Wikimedians

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1539]
## Context

After speaking to folk working on Wikimedia and related projects, there's a lot of desire to use our charts in online and offline articles, but of course many of those articles are in languages other than English.

Although OWID does not intend to translate our site to other languages in the near future, preferring auto-translation instead, we might be able to support smaller changes that allow others to more easily insert translated strings manually when using our charts.

## Things that would help with manual translation

- [ ] #1562
- [ ] Grapher as a standalone library in NPM
- [ ] (low prio) Refactor explorer's UI strings to make them translatable

## Things that would help with automatic translation

- [ ] Audit grapher charts for strings that don't get auto-translated
