### ISSUE TITLE
Tracking issue: values on maps

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1630]
As part of Google Summer of Code, @coder-whale is implementing [annotations on maps](https://github.com/owid/owid-grapher/discussions/1291) (see also #1460). This issue is for tracking the things the we want to check after the project is finished but before we roll it out to the public.

- [x] Merge lerna changes into the feature branch
- [ ] The value for Russia is not visible on the map for Europe
- [ ] We will need an admin option to turn this feature on/off per chart (might still be finished as part of the project)
- [ ] Decide if we also want users to be able to hide annotations when it is turned on for a chart to clear up the view. Would need a checkbox or similar and we don't have much screen real estate
- [ ] Decide if we want the labels on mobile at all
- [ ] Check if the CPU use is acceptable on slower devices or if we have to precompute some things (we could compute centers of largest interiour space and external attachement points in long/lat space and store it as a json)
- [ ] Maps with scales that span large domain ranges can be confusing, e.g. [this one](http://localhost:3030/grapher/deaths-lead-exposure?time=latest&country=WSM~AGO~IND). Should we just not turn this feature on there or can we improve this?
- [ ] The black/white foreground color logic could use some tweaking - isDark that we currently use seems to lead to suboptimal contrast, e.g. [here](http://localhost:3030/grapher/traded-energy-share-domestic?country=CHN~ZAF~IND~USA~GBR~ESP).

**Comment by larsyencken** [comment]
Bumping to the coming cycle, but it's lower prio than the bugs we've already talked about.
