### ISSUE TITLE
Tracking issue: Use cartogramms in grapher

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1631]
@addu390 is working on [generating cartograms for arbitrary years](https://github.com/owid/owid-grapher/discussions/1288) as part of Google Summer of Code. The end product of this project will be a tool that can generate cartogram topoJSON files (or CSV files for the grid) for arbitrary years. To use this in Grapher, we will have to create a new variant of the Choropleth map. 

This issue is about tracking the necessary steps to using cartogramms in Grapher

- [ ] Create a pipeline for postprocessing maps and bundling/fetching them. Currently our map topoJson is hardcoded in [MapTopology.ts](https://github.com/owid/owid-grapher/blob/master/grapher/mapCharts/MapTopology.ts) - this will also help with #1233 
- [ ] Experiment with the temporal resolution for cartograms that we think would be useful. Should we match our entire population dataset? (probably too much). Should we use fixed 10 year jumps? 
- [ ] Decide if topojsons should be loaded on demand or bundled with the grapher component like the current choropleth map
- [ ] Decide if we want to go with fixed population or fluid population mode
- [ ] Decide if we always need an explanatory text for cartograms to help users understand what they are seeing
- [ ] Decide if we always want to be able to toggle between maps and cartograms or if it should be an entirely different chart type (or something in between?)

**Comment by danyx23** [comment]
Might be a good issue to pick up in the Christmas break
