### ISSUE TITLE
Tracking issue: Color in Grapher 

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1673]
This issue is the follow-up for: 
* #1611 

## Grapher config curation work

- [ ] Remove after verification all uses of a few undesirable palettes: 
  - [ ] For map charts remove the following with the help of this notebook https://observablehq.com/@danyx/color-investigations-maps:
      * Inferno
      * Plasma
      * Accent
      * Magma
      * Viridis
  - [ ] For distinct bar charts remove all/most custom color schemes using this notebook: https://observablehq.com/@danyx/color-investigations-non-map-charts-base-scheme
  - [ ] Using the same notebook above remove gradient color schemes for line charts (https://github.com/owid/owid-issues/issues/219)
- [ ] Get rid of custom color choices that use gray to mean something else than "no data"
  - [ ] When used in selected entity colors using this observable notebook: https://observablehq.com/@danyx/custom-colors-by-selected-entity-color
  - [ ] When used for variables using this observable notebook: https://observablehq.com/@danyx/custom-colors-by-variable

## Small coding work to follow up with

- [ ] Consider if adding descriptions to color palettes would be helpful (to be surfaced in the dropdown)
- [ ] Consider if in facetting mode it might be better to switch back to alternating color by enttiy again - the single color bar charts make it harder now to find the same bar in multiple facetted bar charts
- [ ] Add single color continuous scales using color.js (colorbrewer is good but doesn't follow our 5 base colors)
- [ ] Add a note and link in the admin next to the color palette dropdown to link to the notion document with the color choice guidelines
- [ ] Remove obsolete color scales after charts have been migrated away from using them
- [ ] Update the schema with the new list of possible color schemes
- [ ] There is a weird hardcoded orange in some old slope charts (e.g. this chart: https://owid.cloud/admin/test/embeds?ids=415&comparisonUrl=https%3A%2F%2Fourworldindata.org )

## Work to consider for another cycle 

This section collects useful changes that would take more than just a few days to implement:

- [ ] Add support for semantic palettes. A nice way to implement this would be to add the ability for ColorSchemes to map semantic concepts to fixed colors (i.e. values like "coal" or "nuclear"; or "Europe", "Asia"; or "High income countries", ... would be mapped to fixed colors). Then a color column could map to those semantic terms. This would fix the issue we often have on **Marimekko and Scatter plots** where we want to use continents with a stable color mapping but because of how the table is constructed this can shift and then the color assignments are wrong.
- [ ] Replace the ability to choose arbitrary colors with extending the 24 owid-distinct palette with colors from the chosen palette (this would not change anything for some of our own palettes but would add additional colors if a colorbrewer palette is selected)
 - [ ] Create a tool that maps custom colors (entity colors, variable colors, non-palette color assigments in ColorScales) to the closest of the Owid-distinct colors using a perceptual distance metric and enqueue charts with such streamlined color sets into the chart revision tool so that data managers can review if the changes are ok
