### ISSUE TITLE
Mirror `owid-content` to MySQL

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1907]
## What

Mirror explorers in `owid-content` to a MySQL table

## Why

So that we can more safely determine when when charts and variables can be retired.

## Todo

- [x] https://github.com/owid/ops/pull/44
- [x] https://github.com/owid/automation/pull/1
- [x] Get agreement on JSON schema
- [x] Add grapher db migration for explorer schemas
- [x] Tie it all together with a buildkite step

**Comment by larsyencken** [comment]
@marcelgerber @danyx23  I managed to get this working, with open PRs in `automation` and `ops`, and a [Buildkite job](https://buildkite.com/our-world-in-data/mirror-explorers-to-mysql) that watches the `owid-content` repo.

## Demo setup

A live staging setup is running using my staging server `halley`:

- The `owid-content` repo has a branch `halley` that you can clobber, rewrite, force-push, etc to trigger changes
- Buildkite watches for changes, and triggers a `queue=automation` task on a new server, `automation-1` ([automation](https://git@github.com/owid/automation) repo)
- The task runs the `mirror_explorers` script
  - On first run it creates the tables `explorers` and `explorer_charts`, and populates them
  - On subsequent runs it syncs the current explorers in `owid-content` to these tables
- The `.env` file at `/var/lib/buildkite-agent/automation/.env` on `automation-1` currently targets the `halley_grapher` MySQL database on `staging` (see 1password, Engineering vault)

**Comment by larsyencken** [comment]
This is now shipped, and should automatically run on merges to `master` on `owid-content`.
