### ISSUE TITLE
Tracking issue: data pages

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1946]
Data pages are one of our big projects for 2023. It is described in more detail on it's [Notion page](https://www.notion.so/owid/Data-Pages-cd3e69477a40474db975438c93235de9?pvs=4). The project brief is as follows: 

1. Implement a data model that allows data to be tied to the rich metadata needed to properly visualize and understand it. This will allow us to define and maintain the very best rich metadata in one place only, making it more consistent and easier to maintain.
2. Design and implement how this data + rich metadata gets presented in different formats: Data pages, Chartbooks and Standalone Charts
3. As test cases, we will use a number of the Most Important Metrics, as well us some less-well curated variables.
4. The set-up we arrive at does not itself need to be able to work comfortably at scale. But the core logic and key infrastructural choices need to be made with a view to this scaling to hundreds or thousands of variables, following the ‘Technical Text Admin’ project planned for later this year.

Initially we are planning for 2 implementation cycles. The first cycle has these goals:
- [x] #1947
- [x] #1948

The second cycle has the following goals:
- [x] #2120
- [ ] #1995
- [ ] Enable the ArchieML chart component to plot a variable instead of a chart and use them to create a few example chartbooks
- [ ] Upgrade the sources tab of grapher with the variable metadata
- [ ] Test creating page context and partial grapher configs in the ETL for a dataset

We will probably want to add a third cycle for adding some more stretch goals but those are TBD

**Comment by larsyencken** [comment]
Closing this issue, which tracks the first part of the project and is a bit out of date. Let's make a new tracking issue for the current phase.
