### ISSUE TITLE
Tracking issue: developer tooling

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#1972]
# More important

- [x] Replace webpack with vite
	- [x] Ensure vite works well for local development
	- [x] Ensure vite works well when deployed to a staging server
- [x] Ensure all our current scripts work well with vite
- [ ] Speed up the lerna workflow

# Nice to have

- [ ] Consider our future uses of Storybook, and make it work again
- [ ] First steps towards vitest
