### ISSUE TITLE
Switch to new static data API in production

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2131]
## What

Finalise the new data API and switch across to it in production.

## Why / why now

We are considering follow-on work such as powering explorers from variable metadata in the coming cycle. We'd need this working to be able to do that.

## Todo

- [ ] Implement prod and staging endpoints for the new API
- [ ] Switch all new staging environments across to the new API
- [ ] Switch prod over to the new API

## Technical notes

- Until we update the Covid pipelines, the API needs to serve data that originated in `data_values`

**Comment by larsyencken** [comment]
@Marigold Hey, this was on our cycle plan, but just as a placeholder, so I fleshed it out now. Is this still something you think you have time to finish off this cycle?

**Comment by Marigold** [comment]
I have a PR for [cloudflare workers](https://github.com/owid/cloudflare-workers/pull/10) which was the most time consuming piece. Whether I can finish it this cycle depends on how long will review & feedback take.

**Comment by marcelgerber** [comment]
Completed in #2315.
