### ISSUE TITLE
Project Search

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#2254]
<img width="553" alt="a screencap of a searchbar on the OWID home page" src="https://github.com/owid/owid-grapher/assets/11844404/aa7e433b-41b8-4e8d-92c0-39ae08678b0b">

[Figma](https://www.figma.com/file/36r4ZDrt0c4YdOGVduSjQm/[Project]-Search?type=design&node-id=182-15222)

Trying to break this feature down into logical units that will work in a stacked branch workflow.

## Tasks
- [x] [Show explorers in results](https://github.com/owid/owid-grapher/issues/2053)
- [x] Search page route
- [x] Attempt implementation with [InstantSearch](https://github.com/algolia/instantsearch)
    - [x] Search results view
    - [x] Filter results by content type
    - [ ] Filter search by topic (postponed for V2 after [topic categorization](https://github.com/owid/owid-grapher/issues/2325) and tagging effort)
    - [x] Search input UI
- [ ] Homepage searchbar redesign
- [x] Query string integration
- [x] Suggested searches configurability and integration
- [x] Mobile UI
- [x] Recent searches integration
- [x] Keyboard navigation

**Comment by larsyencken** [comment]
Looks like this one is finished up for this year, good to close it Ike?

**Comment by ikesau** [comment]
Indeed! 🥳
