### ISSUE TITLE
Launch the new SDG tracker

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#2331]
## Overview

We want to launch our new SDG Tracker on Tue 18th July. The final pieces need to be in play by then.

## Todo

**Must have**

- [x] Design touchups for the `ChartStory` component #2366 
- [x] A new `align` component to set `text-align` #2367 
	- [x] Content update: Incorporate the `align` component into gdocs content
- [x] Implement [breadcrumbs](https://owid.slack.com/archives/C055SSASSP7/p1683731914068489?thread_ts=1683731587.871309&cid=C055SSASSP7) #2375
	- Some [thoughts about breadcrumbs here](https://www.notion.so/owid/2023-06-26-Thinking-about-breadcrumbs-f7a778df3cf84f6c9a94ed9f5dfa87d4)
- [x] [More robust list parsing](https://owid.slack.com/archives/C03G5HF66DD/p1687172857284519) (for the `AdditionalCharts` block) (part of #2326)
- [x] #2422 
- [x] Content: update the URLs for every page
- [x] #2424
- [x] Update existing, hardcoded links to sdg-tracker.org #2435
- [x] Coordinate launch for Tue 18th July

**Nice to have**

- [x] Ship tooltip redesigns
- [x] https://github.com/owid/owid-grapher/pull/2434
- [x] https://github.com/owid/owid-grapher/pull/2436

After launch:
- [x] #2442
- [x] (optional) trigger an Algolia reindexing, so SDG pages can be found already
- [x] Delete article: https://ourworldindata.org/sdg-tracker
- [x] Delete article: https://ourworldindata.org/sdg-tracker-update

## Context

The [full list is available here as a Google doc](https://docs.google.com/document/d/1D2SZ-IuTHueG8jBCmEpdsiI-0KKvc5fL0jeDdHCuLWY/edit#heading=h.7kago0i2nv5c).

**Comment by larsyencken** [comment]
Closing it! Great job all! \o/
