### ISSUE TITLE
Tracking issue: Drop support for mixed-content explorers

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2374]
Discussion on [Slack](https://owid.slack.com/archives/C0193RW5E2J/p1687856565850549)

### Goal

Drop support for mixed-content explorers

### Summary

- It's currently possible to mix-and-match chart creation methods in explorers (i.e. use grapher ids and csv data files in the same explorer)
- We have three published ([food-footprints](https://owid.cloud/admin/explorers/food-footprints), [natural-disasters](https://owid.cloud/admin/explorers/natural-disasters), [plastic-pollution](https://owid.cloud/admin/explorers/plastic-pollution)) and two unpublished explorers ([biofuels](https://owid.cloud/admin/explorers/biofuels), [covid-test](https://owid.cloud/admin/explorers/covid-test)) that currently do so
- We want to forbid this in the future as it makes explorers generally more error-prone

### To do

- [x] #2504
- [ ] [natural-disasters](https://owid.cloud/admin/explorers/natural-disasters) explorer: has three Grapher IDs only, Pablo has switching to CSV-only on his roadmap for Sept-Nov this year
- [ ] [plastic-pollution](https://owid.cloud/admin/explorers/plastic-pollution) explorer: could be turned into CSV only, currently on the roadmap for August
- [ ] [food-footprints](https://owid.cloud/admin/explorers/food-footprints) explorer:  could be turned into CSV, currently not on the roadmap
- [ ] once the data part is done: drop support on the Grapher side

(the unpublished explorers can be ignored since neither will be published)
(to do's are extracted from the discussion on [Slack](https://owid.slack.com/archives/C0193RW5E2J/p1687856565850549))
