### ISSUE TITLE
Tracking issue: scaling data pages

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2379]
_Things we need to do to sustainably author data pages as part of our work, continuing from owid/owid-grapher#1946._

- [x] Finalise the metadata schema (see: [proposal](https://www.notion.so/owid/2023-06-26-Proposed-metadata-structure-that-enable-data-pages-83b3602d12004796a2034fc870911137?pvs=4))
- [x] Make authoring data pages possible
  - [x] https://github.com/owid/etl/issues/1286
  - [x] owid/owid-grapher#2383
  - [x] owid/owid-grapher#2481
  - [x] owid/owid-grapher#2392
  - [x] https://github.com/owid/etl/issues/1364 - adapt ETL workflow, e.g. propagate Origins when working with Table class and add Origins as default to walkthrough
- [x] Finish data pages core features
  - [x] #2736
  - [x] #2913
- [x] Make authoring data pages routine
  - [x] owid/etl#1474
  - [x] owid/owid-grapher#2482
  - [ ] owid/owid-grapher#2523
  - [x] owid/etl#1666
- [x] Improvements after initial shipping
  - [x] #2740
- [x] Cleanup
  - [x] #2741
- [ ] ~~Enable baking of public data pages via metadata that replace grapher pages~~

**Comment by JoeHasell** [comment]
@larsyencken @danyx23 One thing that is missing (or not prominently featured) from this list is the work on 'tooling' needed to make it easier a) for data managers to fill out the metadata; b) for researchers and data managers to collaborate on the metadata.

Essentially, these were one of our four big bets for the year ('technical text admin'). It feels like our ambition there has implicitly been cut down quite considerably, without us fully reflecting on it.

Perhaps we could discuss this on Weds?

**Comment by larsyencken** [comment]
Hey Joe! I don't think an admin's off the table, but it's more that it might be in addition to, and after, many of the things above. In particular, the Related Research & Writing and Related Data blocks are still outstanding and need to be built. There's also the desire to see what pain points emerge from use, although if we waited for than then an admin would really be post-Porto. 

Perhaps chat next week when Daniel's back?

**Comment by danyx23** [comment]
There is a follow-up tracking issue for work that we decided not to do as part of the Sept/Oct/Nov cycles: #2949
