### ISSUE TITLE
Roadmap: data viz 2023

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2389]
## 2023 Q4

- [ ] ⏳  Data insights: new export formats
- [x] About this data: use new metadata

## 2023 Q3

- [x] Tooltip redesign
- [x] Implement new Grapher designs
- [ ] ~~Chart toggles for derived metrics (per-capita)~~
