### ISSUE TITLE
Roadmap: publication 2023

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2390]
## 2023 Q4

- [ ] ⏳ Sunset Wordpress
  - [ ] ⏳ Migrate old writing to GDocs or HTML
  - [ ] ~~Migrate static pages to GDocs or HTML~~
  - [ ] ~~Remove Wordpress from our infrastructure~~

## 2023 Q3

- [x] #2254 
- [x] GDocs iteration for usability

## 2023 Q2

- [x] Ship first data pages
- [x] Migrate new writing to GDocs
  - [x] GDocs for topic pages
  - [x] GDocs for articles
