### ISSUE TITLE
Set up redirects for old SDG tracker

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2424]
## What

We would like to set up Netlify redirects from the old tracker to the new one.

## Todo

- [x] Get redirects ready to go
  - [x] Redirect root page to https://ourworldindata/sdgs/
  - [x] Redirect each goal page to its matching new goal page
- [ ] Wait: for new tracker to launch
- [ ] Ship redirects

## Technical notes

The old tracker code lives at: https://github.com/owid/sdg-tracker.org

**Comment by ikesau** [comment]
This issue was closed by mistake;  #2422 was meant to be closed instead.

**Comment by marcelgerber** [comment]
Fixed by owid/sdg-tracker.org#42.
