### ISSUE TITLE
Tracking issue: Bake indicators used in explorers

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2438]
Steps:

- [x] add db table that keeps track of indicators used in explorers: https://github.com/owid/owid-grapher/pull/2431
- [x] populate that table on push to `owid-content`: https://github.com/owid/automation/pull/8
- [x] bake indicators used in explorers: https://github.com/owid/owid-grapher/pull/2437

Follow up:

- [ ] #2460

Note that indicators are only baked after pushing to the master branch of `owid-content`. Unsaved explorers and explorers that are not on the master branch will not have their indicators baked. Once we start serving data & metadata JSON files from the Data API instead of baking them, we won't have these problems.
