### ISSUE TITLE
Tracking issue: migrate from Netlify to Cloudflare Pages 

### ISSUE THREAD

**Issue by Marigold** [owid/owid-grapher#2550]
## Tasks

- [x] Set up CF Page in OWID account.
- [x] Implement Algolia configuration and schedule indexing.
- [x] Transition all assets to R2 (replacing S3).
- [x] Enable Deploy queue.
- [x] Implement country redirects.
- [ ] Decide what to do with legacy content like [slides.ourworldindata.org](http://slides.ourworldindata.org/) @Marigold 
  - more [sites on Netlify](https://app.netlify.com/teams/owid/sites)
  - we can either migrate them to CF Pages / deprecate / keep them at free version of Netlify
- [x] Our current feedback button is using netlify function
- [ ] Donate button is using netlify functions
- [x] Covid page is separate and has to be taken care of

## Factors Influencing go/no-go Decision

- [x] Feature parity.
- [x] Comparable performance

## Open Questions
- [ ] Do we want to keep maintaining https://github.com/owid/owid-static?
- [ ] Should we abandon deploy-queue in favour of Buildkite jobs?

## Other things hosted on Netlify

These can _probably_ live on Netlify for some time still, but we will need to move them someplace else at some point.
Also, we should check our contract conditions to see if these will continue to run on Netlify on an (almost) free plan.

- [x] covid.ourworldindata.org hosts Covid data [weird already; this is an auto-deployed Netlify page _that is completely proxied by Cloudflare already_]
  	- Can probably replace it with R2 + CDN? 
- [x] slides.ourworldindata.org and other "small" pages
	- [Get a full overview here](https://app.netlify.com/teams/owid/sites)
- Netlify functions:
	- [x] owid-feedback [[repo](https://github.com/owid/owid-feedback)]
	- [ ] owid-donate [[repo](https://github.com/owid/owid-donate)]
	- Since these are cross-origin requests anyways, these can also continue as Netlify functions for an intermediate time; unless Netlify pulls the plug on us.

## Relevant Links

- **Cloudflare Site (Deployed):** [https://pages.owid.io)
- **Ops PR (includes deploy script):** [https://github.com/owid/ops/pull/75](https://github.com/owid/ops/pull/75)
- **Buildkite Deploy Script:** [https://buildkite.com/our-world-in-data/grapher-deploy/settings/steps](https://buildkite.com/our-world-in-data/grapher-deploy/settings/steps)
- **Deck:** https://www.notion.so/owid/Cloudflare-Pages-8a4e40e2b09547b6aeed9f8087e35d63

**Comment by marcelgerber** [comment]
> there are three new tasks at the top

ah haha, I actually already added these to the issue yesterday - some lines below in the section "Other things hosted on Netlify".

I think these have a lower prio for now, since we can presumably keep them running on Netlify for the time being. But if you feel like whacking a mole, go for them!

**Comment by danyx23** [comment]
Closing this issue as this has happened some time ago now :)
