### ISSUE TITLE
Tasks: About this data

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2752]
Designs on [Figma](https://www.figma.com/file/hGrJi0P2n2TLsUFO2ispxe/%5BProject%5D-Data-Pages?type=design&node-id=1-23&mode=design) | Example charts on [Notion](https://www.notion.so/owid/1ae19e1e749d4701a46b2e4224f1fa8b?v=1fe0c9cead7540fbb660c4b38ec72076)

<details><summary><b>Project outline</b> (click to expand)</summary>

## Background

- This year we completely redesigned our metadata so that we could give people much more context in key places, including the grapher page and the sources tab.
- Traditionally the “tab of shame”, the sources tab was often a dumping ground for various information we wanted to link to indicators.
- The Grapher redesign to ship imminently replaces the sources tab with a metadata overlay, but only an MVP of it will ship at first.

## Goal for this cycle

Ship an upgraded metadata overlay that beautifully renders new metadata when it’s available, and still looks great with old metadata.

## Rabbit holes / scope risk

<details><summary>Old and new metadata</summary>
<br>
 
 - Today, nearly all the metadata shown this way will be old metadata
 - We hope that by year's end, all new or updated charts will have new metadata

**To de-risk:** plan to get to a rendering prototype quickly, then do design iteration from there

</details>

<details><summary>Multi-indicator charts</summary>
<br>
 
 - Some charts have multiple indicators (up to 25 in the worst case)
 - Currently unclear if we want to de-duplicate the metadata if all indicators have a common dataset
 - If we decide not to de-duplicate, we're not currently sure how to best accommodate many indicators in the sources modal

**To de-risk:** plan to get to a rendering prototype quickly, then do design iteration from there

</details>

<details><summary>Hyperlink entry point - OUT OF SCOPE</summary>
<br>

- We changed the entry point to a hyperlink, from a tab
  - We think that many fewer people will click to reveal this information now
- We have resolved not to worry about it this cycle though

</details>

<details><summary>Data page linking - OUT OF SCOPE</summary>
<br>

- We would ideally consider how to link from the sources info to the data page
- But it's out of scope for this cycle
- In any case, clicking on the chart title will take you to the data page if one exists
</details>

## Implementation plan

</details>

### Must have

- ~Build up the necessary UI and components using an example of a well curated indicator with new metadata (best-case scenario; [example](https://owid.cloud/admin/variables/815076))~ Daniel moves Datapage components useful for the sources modal into a shared folder
    - Until we have better solution, simply stack multiple indicators
- [x] Make it work for less optimal cases (potential 🐇 -hole)
    - sparse metadata v2 ([example](https://owid.cloud/admin/variables/813875))
    - old metadata ([example](https://owid.cloud/admin/variables/737650))
    - hybrid metadata ([example](https://owid.cloud/admin/variables/737659))
- [x] Make it work for multiple indicators
    - ~will either be de-duplicated (potential 🐇 -hole) or~ be accounted for (e.g. tabs, dropdown, ...)

### Nice to have

- Support more Markdown syntax: #2758 (Daniel looks into this)

### Stack (ongoing work)

- https://github.com/owid/owid-grapher/pull/2794
  - https://github.com/owid/owid-grapher/pull/2853
    - https://github.com/owid/owid-grapher/pull/2877
      - https://github.com/owid/owid-grapher/pull/2886

### Clean up

- [x] Sources modal and data table should be using the same name for an indicator ([example]( https://ourworldindata.org/grapher/total-financial-assistance-and-flows-for-agriculture-by-recipient?tab=table))
- [ ] Refactor other modals to make use of shared styles (and ignore the base font size)

### Related issues

- https://github.com/owid/owid-grapher/issues/1501
- https://github.com/owid/owid-grapher/issues/2756
