### ISSUE TITLE
Walk through Netlify downgrade checklist

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2819]
## Background

Netlify support provided us with the following downgrade checklist. It's copied verbatim here and turned into tasks.

## Downgrade checklist

For the downgrade to a self-serve plan - here are the instructions and questions to confirm before we proceed.

Have you prepared for the downgrade? There are several preparatory steps the customer should take as advised from our support eng team:

- [x] Have they reduced usage for features that were free on Enterprise but are not on lower plans? Things like Analytics, Identity level 1, etc will be line item costs every month on a lower plan.
- [x] Have they accounted for the removal of paid features such as password protection? A downgrade below Pro will remove it with NO other warning to the customer, only their previously locked down site open to the public.
- [x] At a high level, they need to review usage and ensure that what remains is what you intend to remain - from DNS hosting, to that out-of-sight-out-of-mind internal test site, it is pretty easy to "accidentally" leave stuff active you didn't intend to.
- [x] Have they adjusted any EXTERNAL DNS pointing to Netlify from the Enterprise pattern (<theirname>.[netlifyglobalcdn.com](http://netlifyglobalcdn.com/)) to the self-serve pattern (<sitename>.[netlify.app](http://netlify.app/))? Do you see all "yellow warning triangles" in the site listings in our UI, showing deactivated HP Edge status? If they don't do this, their sites will not be served reliably after the downgrade.
- [x] Have they removed all team members they don't want to pay for from the Team settings page?
- [x] Have they disconnected all repositories from sites (or Stopped builds on any connected sites), or do they have a plan to constrain your build minutes usage to their new lower allocation?
- [x] Have they ensured that no sites remain online that might be attacked or cause bandwidth overages unexpectedly?
- [x] Before we proceed with the downgrade, the customer should be aware that:
  - they'll lose all enterprise features like forced SSO, HP Edge, HP Build, etc
  - they will IMMEDIATELY be charged on the card in the UI if there are any paid features remaining on their account from extra collaborators to Identity level 1 (they will need to make sure they have a credit card on file).

**Comment by marcelgerber** [comment]
Went through all of these now, we're good now!

We're gonna continue using the `owid-donate` function for the time being (phasing it out once #2737 launches, probably). I couldn't find definite info on whether we're gonna have to pay for that or if it's covered by the free plan (we're currently using "Functions Level 2" with no way to downgrade), but will check that tomorrow again.
If we're continuing paying then it's not gonna be much.
