### ISSUE TITLE
Tracking issue: improving the indicator and dataset admin

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3002]
This issue is a placeholder/shopping list of things we could want to do here, in no particular order:

- [ ] Rename `/admin/variables` to `/admin/indicators`
- [ ] Improve the Indicators search page
  - [x] Display `catalogPath` for every indicator row
  - [x] Search in `catalogPath` field and highlight matches there
  - [x] Change layout so that long catalog paths don't break the table
  - [x] Support `path:` query limiting to only search catalog path
  - [ ] ~~TF-IDF style re-ranking of search in the variable admin~~
  - [ ] Link every catalog path segment to a search on that prefix
- [ ] Improve the Indicator edit page
  - [ ] https://github.com/owid/owid-grapher/pull/3106
  - [ ] List any data pages separately and above any charts
  - [ ] List any indicator-based explorers separately and above any charts
- [ ] Improve the Datasets page
  - [ ] Give every dataset a `catalogPath` in the admin
  - [ ] Add the `shortName` to the variables list in the datasets page
- [ ] Improve the Dataset edit page

**Comment by mlbrgl** [comment]
@danyx23 @ikesau triaged

**Comment by larsyencken** [comment]
Updated now, a few things here had been done, and indicator metadata editing is in progress.
