### ISSUE TITLE
Roadmap: publication 2024

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3040]
[← 2023](https://github.com/owid/owid-grapher/issues/2390) | [↑ Engineering](https://github.com/owid/engineering/issues/39)

## 2024 Q1

- [x] #3277
- [x] https://github.com/owid/owid-grapher/issues/3097

## 2024 Q2

- [x] https://github.com/owid/owid-grapher/issues/2852
- [x] #3278
- [x] https://github.com/owid/owid-grapher/issues/2485

## 2024 Q3

- [x] #3781 
- [x] #3861 

## 2024 Q4

- [x] #4002 
- [x] Admin for redirects
- [ ] Redo About pages as Gdocs

## Candidates

- [ ] Improve the dev experience (faster hot reload)
- [ ] Improve the testing strategy
- [ ] Clean up internal GDocs API access
- [ ] Enable local-offline development
- [ ] Finish conversion of `owid-grapher` into our Typescript monorepo
