### ISSUE TITLE
Roadmap: data viz 2024

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3041]
[← 2023](https://github.com/owid/owid-grapher/issues/2389) | [↑ Engineering](https://github.com/owid/engineering/issues/39)

## 2024 Q1

- [x] Add an indicators block to the homepage

## 2024 Q2

- [x] [Update the entity selector for Grapher](https://github.com/owid/owid-grapher/issues/3349)

## 2024 Q3

- [x] #3766 
- [x] #3795

## 2024 Q4

- [x] Toggle between line and slope charts
- [x] Focus states for line charts

## Candidates

- [ ] Entity types and hierarchies
- [ ] Mark some charts as indicators
- [ ] Choice of ordering for bar charts (e.g. order by name, order by value, asc, desc)
- [ ] Make Grapher a standard React component
  - [ ] Extract data loading and state from Grapher
