### ISSUE TITLE
Tracking issue: Mobile Grapher

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#3070]
- [x] https://github.com/owid/owid-grapher/issues/3010
- [x] https://github.com/owid/owid-grapher/issues/2887
- [x] https://github.com/owid/owid-grapher/issues/3011
- [x] #3136 is also related
- [x] StackedBar: Display legend on top of the chart on mobile

Other issues:

<details><summary><s>"Show selection only" toggle almost overlaps with content switchers</s></summary>
<p>

Example chart: https://ourworldindata.org/grapher/electricity-as-a-share-of-primary-energy?tab=table

<img width="317" alt="Screenshot 2024-01-05 at 16 23 47" src="https://github.com/owid/owid-grapher/assets/12461810/fd09223a-d9cd-486d-9109-7c0a28927114">
</p>
</details> 

<details><summary><s>On data pages, Grapher should bleed onto the edges horizontally, similar to how it's done on Grapher pages and in articles</s></summary>
<p>

Example chart: https://ourworldindata.org/grapher/electricity-as-a-share-of-primary-energy?tab=table

<img width="370" alt="Screenshot 2024-01-05 at 16 25 24" src="https://github.com/owid/owid-grapher/assets/12461810/1961bd9e-2902-4123-bcad-11646ab6843a">

</p>
</details> 

<details><summary><s>Unnecessary single-item legend takes up vertical space</s></summary>
<p>

Example chart: https://ourworldindata.org/grapher/death-rate-by-cause-who-mdb?facet=metric

<img width="370" alt="Screenshot 2024-01-05 at 16 31 30" src="https://github.com/owid/owid-grapher/assets/12461810/177f0ae1-8937-4334-b446-8dea61c00efb">

- Related: https://github.com/owid/owid-grapher/issues/2594

</p>
</details> 

<details><summary><s>Tooltip overflows</s></summary>
<p>

Example charts:
- https://ourworldindata.org/grapher/co2-emissions-fossil-land
- https://ourworldindata.org/grapher/distribution-of-population-between-different-poverty-thresholds-up-to-30-dollars

<img width="363" alt="Screenshot 2024-01-15 at 08 30 54" src="https://github.com/owid/owid-grapher/assets/12461810/f78ead28-37e2-4e8c-99f1-25a894e4d507">

</p>
</details> 

<details><summary><s>Entity selector: Allow to clear the input field</s></summary>
<p>

Slack: https://owid.slack.com/archives/C0149NKLZAM/p1705351087477649

</p>
</details> 

<details><summary><s>Unused space next to the legend on the right</s></summary>
<p>

Example chart: https://ourworldindata.org/grapher/number-of-nuclear-weapons-tests

<img width="388" alt="Screenshot 2024-04-15 at 09 58 46" src="https://github.com/owid/owid-grapher/assets/12461810/7fc48f97-5e2a-42d4-89a8-68ffac0a98a1">

</p>
</details> 

<details><summary>Scatter legend is scrambled</summary>
<p>

![image](https://github.com/owid/owid-grapher/assets/12461810/507d0543-0240-4bab-9eed-7231772471d0)

</p>
</details> 

<details><summary>Mobile static DiscreteBar chart: Labels too big and slightly misaligned</summary>

![annual-research-development-funding-for-neglected-tropical-diseases](https://github.com/owid/owid-grapher/assets/12461810/84d8bb26-a4a3-40be-b79c-80fb6b8f97dc)

<p>

</p>
</details> 

<details><summary><s>Full screen button appears/disappears when scrolling up and down</s></summary>

<p>

Example: https://ourworldindata.org/grapher/remaining-life-expectancy-at-different-ages-males

This happens because we use the `innerHeight` to determine whether the full screen button should be shown. But the `innerHeight` updates when the URL bar is shown/hidden on mobile.

</p>
</details>

**Comment by sophiamersmann** [comment]
Most of the points have been addressed. The open issues are very small and don't necessarily need to be tracked
