### ISSUE TITLE
Tracking issue: author pages

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#3224]
## Plan & scope for (short) 2024.2 cycle
Ship the author page template powered by a slightly modified research and writing block from topic pages:
- [x] #3256 
  - [x] mobile/responsive styles
  - [x] dark version
- [x] #3257
  - [x] mobile/responsive styles
  - [x] add publication date to thumbnails in latest
  - [x] remove duplicate featured articles from latest
  - [x] handle missing featured images in work section
  - [x] #3264
  - [x] #3265
  - [x] #3263 
  - [x] #3302 
  - [x] remove authors
- [x] Infra/devops:
  - [x] #3282 
  - [x] #3310 

---- 🌑 dark launch (authors can start creating their own author page) - ✅ Friday, March 15, 2024

- [x] #3322 

👇 Checked items below are reviewed and available on [staging](http://staging-site-author-pages-launch/gdocs/1VDcqVRkbi7dYI0xI9m3AQmp14xCEy9UukJoD6n3rHtE/preview)
- [x] manually curated pill row: max 5, multiple lines on desktop, swipe on mobile
- [x] pill row: the title above the pills should not scroll with the pills but should be fixed ([slack](https://owid.slack.com/archives/C06KFK86HST/p1712907694373349?thread_ts=1712850248.918149&cid=C06KFK86HST)) 
- [x] 🐛 author font size on mobile ([slack](https://owid.slack.com/archives/C06KFK86HST/p1710861958052469?thread_ts=1710423945.447979&cid=C06KFK86HST))
- [x] spacing and font sizes for headings ([slack](https://owid.slack.com/archives/C06KFK86HST/p1710417040272619))
- [x] add bsky, threads, mastodon to socials ([slack](https://owid.slack.com/archives/C06KFK86HST/p1710883748872889?thread_ts=1710881845.753219&cid=C06KFK86HST), [slack](https://owid.slack.com/archives/C06KFK86HST/p1710885419122489), [figma](https://www.figma.com/file/Tm4bd2QXmrAR4m7UfWKAle/Author-Page?type=design&mode=design))
- [x] fix image missing regression
- [x] underline social links on mobile ([slack](https://owid.slack.com/archives/C06KFK86HST/p1712907870869429?thread_ts=1712850248.918149&cid=C06KFK86HST))

---- 🚀 public launch possible from Monday, April 22, 2024 (author pages have the minimum elements required to be shown publicly)

## Candidates for next scope

Migrated to:

- #3580 

## Context
- figma: [author page](https://www.figma.com/file/Tm4bd2QXmrAR4m7UfWKAle/%5BProject%5D-Author-Pages?type=design&node-id=126-3896&mode=design&t=VsRG09NTbvTOHCw7-0), [team page](https://www.figma.com/file/9bQW46okOjxeJtismQQdPu/%5BDesktop%5D-Screens-1.0?type=design&node-id=1805-14745&mode=design&t=hhZ0AYzs6PJrd5Nx-0) (slightly outdated, e.g. no teams anymore but alphabetical order)
- [scoping notes from Feb 27](https://www.notion.so/owid/P-D-and-engineering-meeting-notes-3a0cb73df3624beeb65ee8cf1b1470d7?pvs=4#b3da0399ab6a497ba073457406d50805)
- slides

**Comment by larsyencken** [comment]
Hey @mlbrgl , closing this one and migrating the remaining tasks to #3580, a new issue for this cycle.
