### ISSUE TITLE
Tracking issue: SVG tester

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#3309]
An unordered collection of low- and high-effort tasks to make our SVG tester even better (fell out of a discussion with Daniel)

- [x] Move SVG tester GitHub actions to Buildkite jobs that run on our machines
    - On GitHub machines, the SVG tester takes ~10min; on foundation, it takes ~5min

- [ ] Now that our SVG tester system grows (e.g. we just added a second GitHub action that tests hidden views), we might benefit from building our own infrastructure and moving away from the `owid-grapher-svgs` repo

- [ ] Compare SVGs to the parent branch, which in a stack of PRs is not necessarily the master branch
    - e.g. in a stack `master` – `first-branch` – `second-branch`, `second-branch` would be compared to `first-branch` and `first-branch` would be compared to `master`

**Comment by danyx23** [comment]
@sophiamersmann this issue seems stale - do you want to update it or close it?

**Comment by sophiamersmann** [comment]
I'll close this one and open a new one for the last item on the to-do list.
