### ISSUE TITLE
Cycle 2024.2: technical search improvements

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3330]
## Goal

Improve the quality of search results returned by our existing search, as exposed on our homepage and in the site header.

## Scope

**Must do**

- [x] owid/ops#158
- [x] owid/owid-grapher#3332
- [x] Verify that all relevant Algolia settings are in code
- [x] #2932
- [x] #3378
- [x] #3402
- [x] #3416
- [x] Detect and dynamically thumbnail geographical entities #3388 
	- [x] #3401
- [x] #3377
- [x] #3429 
- [x] Feature branch PR: #3497 

**Should do**

- [x] https://github.com/owid/owid-grapher/issues/3380
- [x] Use thumbnail placeholders in search UI #3371
- [x] #2852 

**Not this cycle**

- [ ] Include headings, key insights, SDG targets etc. in search index `posts`
- [ ] #3383
- [ ] #3442
- [ ] Get pageviews for all explorer views for ranking
- [ ] Make a standout data search result an interactive chart
- [ ] Power user filters for search
- [ ] Improve how search results are tagged in the output
- [ ] Replace country pages with search results
- [ ] Add data-specific filters to the search results
- [ ] Improve the layout of data search results
