### ISSUE TITLE
Tracking issue: Search improvements

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#3572]
Just a bunch of things that I haven't had time to finish as part of #3330.

- [ ] Write tests for [`extractCountryName`](https://github.com/owid/owid-grapher/blob/c9a9bd8b2a321a94372dcc3c487c88ae49531817/site/search/SearchUtils.tsx#L24-L29)
- [ ] Automatically expand a section when there's only a single section available
- [ ] Provide a set of allowed suffixes to match, like `(WHO)`
- [ ] Special design of SDG results in R&W results
- [ ] Index data insights
- [ ] For R&W, add headings, key insights, etc. to the search index for more relevant results
- [ ] Add synonym treatment for "High-income countries" <-> "High-income" etc.
