### ISSUE TITLE
Cycle 2024.4: Parent-child relationships

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#3766]
## Implementation plan

- [x] Add a table for chart configs, using UUIDs as primary key
  - [x] Populate `chart_configs.fullConfig` for all existing charts
- [x] Add the default config to the database that every chart inherits from
  - [x] Populate `chart_configs.patchConfig` for all existing charts
  - [x] Update the admin API to handle inheritance from the default config
- [x] Add indicator charts and implement implicit inheritance
  - [x] Point `variables.grapherConfigETL` and `variables.grapherConfigAdmin` to a row in the `charts_config` table
  - [x] Update the admin API to handle implicit inheritance from indicator charts
  - [x] Check all existing charts [2d]
- [x] Make the chart editor work with inheritance [2d]

Follow-up work: https://github.com/owid/owid-grapher/issues/3857

---

PRs to be merged when adding a `chart_configs` table:
- Grapher: #3767 
- ETL: https://github.com/owid/etl/pull/2957
- Datasette: https://github.com/owid/analytics/pull/138
- Schema validation: https://github.com/owid/automation/pull/12
