### ISSUE TITLE
Cycle 2024.4 Friendly Data Catalog

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#3781]
[Figma](https://www.figma.com/design/AXOlKddXgQvUnRv3FfhlyM/Data-Catalogue?node-id=1-824&t=MM5mCLWSlsNugwFu-0)

**TODO**:
- [x] Set up correct tag graph on prod
- [x] Create Algolia Staging index and update indexer tag structure that works with drilling down (3d)
- [x] Bare bones explore + search UI (search; tag drilldown; breadcrumbs; "browse by tag" section) (3d)
- [x] URL state serialization (1d)
- [x] Country faceting UI (an entity selector to begin with) (1w)
- [x] UI polish (3d)
- [x] Baking/sitemap (1d)

**Unexpected work**
- [x] Design exploration for tag/folder navigation (3d)
- [x] Pagination (3d)
- [x] Fix internal state representation
- [x] Fix query string parsing when tag names have commas in them
- [x] Mobile UI customizations (3d)

**Next cycle, probably**:
- Tag cloud faceting (needs more discussion) (1w, some uncertainty here) 
- DSL with pills (depends on country and tag faceting decisions)
- Autosuggestions
- Explorer data (grapher-based and MDMs)
- Thumbnails for explorers
- Analytics

**Things to think about**:
https://github.com/owid/owid-grapher/issues/3648 will allow us to list data downloads at a higher level

**Cooldown simpatico**:
- Update the [sitenav tag graph branch](https://github.com/owid/owid-grapher/compare/sitenav-from-tag-graph?expand=1) to use subareas and perfectly recreate the static site nav ontology in the prod tag graph so that there's no delta when merged. d&r can then update the tag graph on prod as they wish. (3d)
