### ISSUE TITLE
Cycle 2024.4: Multidimensional data pages

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#3795]
## Implementation plan

Current prototype PR: #3657 

## Must-haves

- [x] Extract React components from existing data pages
- [x] URL serialization/deserialization
    - [x] Sensible behaviour if one of the URL params is invalid
    - [x] Load view immediately, even if no URL params present
- [ ] Various baking steps - e.g. SQL queries, hydration
	- [x] Provide `faqEntries`
	- [x] Provide `tagToSlugMap`
	- [x] Resolve catalog paths to variable IDs
	- [x] `primaryTopic` for citation information
	- [ ] How to serialize grapher config? And where to get overrides from? API endpoint?
		- Create dict: view to grapher config UUID, then fetch clientside on demand [4h]
	- [ ] Image metadata [4h] (see #3862)
	- [ ] `relatedResearch`
	- [ ] `allCharts`
	- [ ] Include thumbnail image
	- [ ] Performance improvements / caching for baking
	- [ ] ... anything else?
- [ ] Make code ready for review [1d]
	- [x] Unify `_OWID_MULTI_DIM_CONFIG` and `_OWID_DATAPAGEV2_PROPS` under a single object
	- [x] Add README explaining lingo (dimension, choice, view, choice group, ...)
	- [ ] Add config schema
- [x] Add `.env` feature flag
- [x] UX changes for long dropdowns: search bar or scrolling
- [ ] UI improvements [1.5d]
	- [x] Don't break lines in strings if window too narrow
	- [ ] How to break "Configure the data" row if too wide? [2h]
	- [ ] Update page title as user navigates [1h]
	- [ ] Focus/hover states [2h]
	- [x] Supply data page title by default
	- [ ] Radio button padding is not clickable [0.5h]
	- [ ] Make changing between views less jumpy above-the-fold [2h]
	- [ ] Unavailable radio buttons should be disabled, not hidden [1h]
- [ ] What things should go in MDD config?
	- [x] Default selection
	- [x] Probably: Topic page tags
	- [x] Probably: Data page title?
	- [ ] Allow for overriding origin metadata / "About this data" section [4h]

## Should-haves (will need these at some point!)

- [ ] Mobile styles [may be large project]
- [x] Authoring
	- [x] Come up with final `variableIds` format that we can then support
	- [x] Support catalog paths
- [ ] Save things in DB?? [can do this after launch]
- [ ] Enable embedding MDDs [can do this after launch]
	- [ ] ... with and without select dropdowns

**Comment by marcelgerber** [comment]
Superseded by #3874, closing.
