### ISSUE TITLE
About Page gdocs migration tracking issue

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#3853]
We have an [about page template](https://github.com/owid/owid-grapher/commit/ebbaf7ef33cb7d67ad25ae64da1efd999e8c43e8)

But we're missing some components in order to implement [Marwa's designs](https://www.figma.com/design/kgwh14s9hheiWp7ajWUolJ/About-Pages?node-id=61-3355&t=32yAdjeX0aSH7kiW-0):
- [ ] Subnav
- [ ] Team member profiles
- [ ] Accordion
- [ ] Donor section
- [ ] Article tiles (possibly just a variant of prominent links, but we'd need a way to put them side-by-side in a grid)
- [ ] Gray contact us box (possibly negotiable)

Once that's done, the new articles will also need to be created which is probably a larger task for the whole org (though a dev can create the initial pages)

**Comment by ikesau** [comment]
https://github.com/owid/owid-grapher/issues/1262 will probably get done as part of this

**Comment by danyx23** [comment]
We're scoping this as a proper project ATM in Notion, closing this issue here that will eventually be replaced by a cycle issue.

https://www.notion.so/owid/About-pages-91b43ac2b5db4598b6276b51b324931c?pvs=4
