### ISSUE TITLE
Cycle 2024.5: Parent-child relationships in the admin

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#3857]
[Previous cycle](https://github.com/owid/owid-grapher/issues/3766)

## Implementation plan

- [x] Surface inheritance in the chart editor for "normal" charts
    - [x] Add a new "Inheritance" tab in the chart editor [4h]
    - [x] Surface parent values in the chart editor [2d]
- [x] Allow indicator charts to be edited via the admin
    - [x] Add buttons to create/go-to/delete indicator charts on a variable page [1h]
    - [x] Add new routes that allow editing an indicator chart [2d]
