### ISSUE TITLE
Tracking issue: Multidimensional data pages

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#3874]
Previous cycle's (2024.5) planning issue: owid/owid-grapher#3877
Current cylce issue (2024.6): owid/owid-grapher#4007 

---

## Launch blockers 

- [x] mobile styles (e.g. dropdowns get cut off)
- [x] nicer UI while switching indicators (nicer chart title; less jumpy UI below chart)
- [x] ability to override metadata for single views (especially relevant for ones with multiple y-indicators)

## Cycle 2025.01 goals
(roughly sorted by priority)

### Must have
- [x] https://github.com/owid/owid-grapher/issues/4454
   - [ ] Consider whether we add mdims also to `/search`
   - [x] https://github.com/owid/owid-grapher/issues/4456
- [x] https://github.com/owid/owid-grapher/issues/4455
- [x] https://github.com/owid/owid-grapher/issues/4457
- [x] https://github.com/owid/owid-grapher/issues/4458
- [x] https://github.com/owid/owid-grapher/issues/4540
- [x] https://github.com/owid/owid-grapher/issues/4482
- [x] owid/owid-grapher#4040
- [x] https://github.com/owid/owid-grapher/issues/4459
- [x] https://github.com/owid/owid-grapher/issues/4519
- [x] owid/etl#3800

### Should have
- [x] Title and description meta tags
  - We need to set it correctly for the initial load (during baking or in a worker?) it can be out of sync after dropdown change
 - [ ] Various baking steps - e.g. SQL queries, hydration
  - [ ] Image metadata [4h] (see owid/owid-grapher#3862)
  - [x] Include thumbnail image
  - [x] Provide `canonicalUrl`
  - [ ] The page should work with disabled JS - fallback image for grapher + static elements, similar to normal data page
    - Probably just a proper warning that JS is needed rather than making the image fallback work - that would make more sense when we render the whole page dynamically in a worker
- [ ] Small UI/UX fixes
  - [ ] If only one dropdown options is possible, disable the dropdown
  - [x] owid/owid-grapher#4232 
  - [ ] Focus/hover states [2h]
  - [ ] Radio button padding is not clickable [2h]
  - [ ] Unavailable radio buttons should be disabled, not hidden [1h]
  - [ ] Dropdown might [overflow to the right](https://github.com/owid/owid-grapher/pull/4704#pullrequestreview-2726079233) [3h]
- [ ] Add analytics view event so that every drop down change results in a new analytics view event
  - Related: https://github.com/owid/analytics/issues/160
- [x] owid/owid-grapher#4121
- [ ] Performance improvements / caching for baking

## Potential goals for later cycles:
- [x] #4774
- [ ] Add search for dropdown options (for long lists)
- [ ] https://github.com/owid/owid-grapher/issues/4771

## Could haves
- [ ] Non-ETL editing workflow (could be a bit like the explorer admin spreadsheet view)
- [ ] Add checkboxes and/or consider radio buttons? E.g. when you have a "per capita/absolute" toggle where you would like to see both options immediately
- [ ] Make mdim views show up in the all charts block?

**Comment by marcelgerber** [comment]
Closing this, as it's been superseded by #4007.

**Comment by lucasrodes** [comment]
re: 
> Add checkboxes and/or consider radio buttons? E.g. when you have a "per capita/absolute" toggle where you would like to see both options immediately
 
We have been migrating some explorers in ETL to have an MDIM-like config. For these, we need to specify if we want dropdowns, checkboxes, radio buttons, etc.

As an example: [Monkeypox](https://github.com/owid/etl/blob/405e59ae8e0ecbe9bd00d0e57532d94df1365391/etl/steps/export/explorers/who/latest/monkeypox.config.yml#L69-L78).

For it to be compatible with current MDIM config structure, we've added a new attribute under a dimension called `presentation`, which has a `type` that specifies the UI (radio, dropdown or checkbox). If it is a checkbox, then an extra property `presentation.choice_slug_true` is expected, that points to the dimension choice slug that stands for "checked".

The complete example, with three dimensions: `metric`, `frequency`, and `scale`, where the last one is a checkbox.

```yaml
dimensions:
  - slug: metric
    name: Metric
    choices:
      - slug: confirmed_cases
        name: Confirmed cases
      - slug: confirmed_and_suspected_cases
        name: Confirmed and suspected cases
      - slug: confirmed_deaths
        name: Confirmed deaths
    presentation:
      type: radio
  - slug: frequency
    name: Frequency
    choices:
      - slug: _7_day_average
        name: 7-day average
      - slug: cumulative
        name: Cumulative
      - slug: daily
        name: Daily
    presentation:
      type: radio
  - slug: scale
    name: Relative to population
    choices:
      - slug: absolute
        name: "Total population"
      - slug: relative_to_population
        name: "Relative to population"
    presentation:
      type: checkbox
      choice_slug_true: relative_to_population
```
