### ISSUE TITLE
Tracking issue: Refactor site deployment

### ISSUE THREAD

**Issue by Marigold** [owid/owid-grapher#3985]
Our deployment process is unnecessarily complex right now. We haven't changed it when migrating from Netlify to Cloudflare and there easy ways how to simplify it:
- [ ] Our site is built into `~/live-data/bakedSite`, it could be just `~/bakedSite`
- [ ] Deploy scripts are in `owid-grapher` repo, but it'd be more natural to have them in `ops` (since they are similar to staging servers)
- [ ] Is the 20000 file limit by Cloudflare still relevant (as a workaround we serve those files from R2)? There's `grapher/exports` that contains ~9000 files which can make it impossible

**Comment by danyx23** [comment]
In #3746 Ike tried to get rid of one of the main uses of static chart thumbnails (the other being chart admin preview images). We are a lot closer to being able to delete the static charts now but it would mean reviving that PR and bringing it over the finishing line.

**Comment by danyx23** [comment]
The first two points I think you can just do, @Marigold, there is no good reason not to. The third point needs a bit of work on the Grapher side.

**Comment by Marigold** [comment]
Thanks for the heads-up. It's by no means important, serving files from R2 has been working surprisingly well.

**Comment by Marigold** [comment]
Closing as not important. The 20k limit for uploaded files still exist, but it's not a big deal since our R2 workaround works well enough.
